apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: walmart-app
  name: walmart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walmart-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: walmart-app
    spec:
      containers:
      - image: localhost:5000/walmart-app:1.0.4
        name: walmart-app
        ports:
        - containerPort: 80
        resources: {}
        env:
        - name: PORT
          value: "80"
status: {}
